### ISSUE TITLE
Rename the String class for PHP 7.0

### ISSUE THREAD

**Issue by tomzx** [vierbergenlars/php-semver#42]
Under PHP 7.0, classes named as *String* are not allowed. As such, it will generate a fatal error that looks like this:

PHP Fatal error:  Cannot use vierbergenlars\LibJs\String as String because 'String' is a special class name in /home/travis/build/tomzx/php-semver-checker-git/vendor/vierbergenlars/php-semver/src/vierbergenlars/SemVer/internal.php on line 5

**Comment by vierbergenlars** [comment]
I thought only `\String` was not allowed as a class name.
Does changing the `use` statement fix it or should the class be renamed?

**Comment by tomzx** [comment]
Based off http://3v4l.org/dkvXT, it appears that that in April the behavior changed from allowing the \String class to not allowing it anymore. Thus the answer would be that you need to rename the class itself.

**Comment by vierbergenlars** [comment]
Fixed in 516bb30
