### ISSUE TITLE
Move to PHPUnit

### ISSUE THREAD

**Issue by tomzx** [vierbergenlars/php-semver#43]
Hello,

Would you have any objection to move from `SimpleTest` to `PHPUnit`?

**Comment by vierbergenlars** [comment]
I would actually be very happy to move to PHPUnit, but never really bothered because it would take me too much time.

You are more than welcome to help, if you like!

**Comment by tomzx** [comment]
I don't think it should be too much work. Since you don't have any issue with the change, I'll get started as soon as I can.

**Comment by vierbergenlars** [comment]
:+1: Thank you very much
