### ISSUE TITLE
Use of deprecated each in JSArray

### ISSUE THREAD

**Issue by mdio** [vierbergenlars/php-semver#56]
I would like to bring to your attention that the function [each](https://www.php.net/manual/en/function.each.php) (used in [JSArray](/vierbergenlars/php-semver/blob/master/src/vierbergenlars/LibJs/JSArray.php#L197)) has been deprecated as of PHP 7.2 and "Relying on this function is highly discouraged".
To my knowledge the removal has not been scheduled, yet.

**Comment by vierbergenlars** [comment]
Fixed in #59
