### ISSUE TITLE
Release the last commit

### ISSUE THREAD

**Issue by RobinDev** [vierbergenlars/php-semver#60]
Hello,

Is it possible to release the last commit avoiding php warning on version 8 ?

Thanks

**Comment by vierbergenlars** [comment]
Thanks for letting me know, I forgot about that.

https://github.com/vierbergenlars/php-semver/releases/tag/v3.0.3

**Comment by RobinDev** [comment]
Weird, it was not published on packagist https://packagist.org/packages/vierbergenlars/php-semver

**Comment by RobinDev** [comment]
Just did it, sorry for the useless noise.
